### ISSUE TITLE
freeze effect remains on the player indefinitely

### ISSUE THREAD

**Issue by GitJhopa** [infernalexp/Mining-Master#48]
### Describe the Bug

I use a mod for regions where you can turn off PVP. For example: https://legacy.curseforge.com/minecraft/mc-mods/open-parties-and-claims and when I try to hit a player with a sword with a freeze enchantment, he starts shaking endlessly from the cold and this does not disappear until he rejoin the server or not go into the fire.

### Reproduction Steps

1. Create a region and turn off PVP mode
2. Hit any player in a region where PVP is disabled with a Freeze Enchantment Sword
3. Everything, now he will always shake from the cold
...

### Expected Result

I believe that the effect should not be applied if PVP is not possible.

### Operating System

Windows 10

### Mod Version

3.0.7

### Minecraft Version

1.19.2

### Forge Version

1.19.2-43.2.14

**Comment by Dariensg** [comment]
It's hard for me to test this since I don't have this specific mod or multiplayer to test on, but it seems like based on the code I've looked at, the effect should not apply. In either case, the effect just uses the Vanilla Freezing ticks from powder snow, so it should wear off no matter what. I think you must have a mod that is breaking the freezing effect from Vanilla given your other Freezing related issue which I cannot replicate.

**Comment by GitJhopa** [comment]
I'm in a region where PVP is disabled, and if you hit a player, there is no freeze effect. But the player is shaking from the cold.

**Comment by GitJhopa** [comment]
Now I will shoot you a video, installing only your mod and Open Parties Claims, if that this bug works with all mods for regions. for example Flan mod.

**Comment by Dariensg** [comment]
I'd appreciate a video, yeah!

**Comment by GitJhopa** [comment]
Wait 5-10 mins brooo

**Comment by GitJhopa** [comment]
https://youtu.be/UminQ4VFdqY

**Comment by Dariensg** [comment]
Thanks! I've identified this as a client/server desync and will work to fix it in the next week or so.
