### ISSUE TITLE
[Compat] Tetra compatibility

### ISSUE THREAD

**Issue by StrangerSon71** [infernalexp/Mining-Master#5]
Tetra tools are unable to receive enchantment gems in the Smithing Table, meaning Tetra tools can't obtain the exclusive enchants without an external disenchanter, and even then it won't accept it. Options include adding the ability to input the gems instead of books in the 'Enchant" section or allowing gems to be socketed to provide the enchant. Both options require Tetra tools being able to accept the enchants in the first place (A sword enchanted with Leaching and then converted to a Tetra tool loses that enchantment currently)

**Comment by Dariensg** [comment]
I'll look into that compat! For now, I have a test jar that it would be great if you could test the last bit on. I think it should work with this test file, but I'm not 100% confident. If you could do that, that would be great! Thank you so much!
[miningmaster-1.16.5-2.0.0.zip](https://github.com/infernalexp/Mining-Master/files/7679230/miningmaster-1.16.5-2.0.0.zip)

**Comment by StrangerSon71** [comment]
Thanks a lot!

**Comment by StrangerSon71** [comment]
The test jar file doesn't appear to fix the lost enchantment upon conversion issue, is that what you were asking about?

**Comment by StrangerSon71** [comment]
And now Spirit Garnet can't be applied to a sword (Trident works fine, Fire Ruby works on sword).

**Comment by Dariensg** [comment]
That is what I was asking! Thanks for testing that for me! I’ll have to look into it a little bit closer and see what I do. Thanks for letting me know about the spirit garnet on a sword issue as well. That was a WIP build, but I wasn’t aware of that bug in particular.

**Comment by StrangerSon71** [comment]
Update: Gems can be applied in the Smithing Table, but unregistered enchantments (Leeching) cannot. Registering Leeching and other enchantments to Tetra tools is the scope of this compat.

**Comment by Dariensg** [comment]
Thanks for letting me know! I'll try and get that into the 2.1 release I'm working on for Modpack compat tools.

**Comment by Dariensg** [comment]
I wanted to give you a quick update. I've just had a conversation with Mickelus, the developer of Tetra. As it turns out, the closest we can actually get things functioning right now is that the gems can be applied to a Vanilla tool. Then, when that tool is converted to a Tetra tool, the enchantment will persist. It's not currently possible with the way that Tetra is written to A) Make it so the gems can be applied to a Tetra tool in the Smithing Table or B) Make the gem socket on a Tetra tool to apply the enchantment. Mickelus did say that I will be notified if something is figured out. So, I'll include this initial, half-baked compat into 2.1 that allows the Enchantments to be carried over onto Tetra tools, but unfortunately I can't do anything more integrated than that as of right now. My apologies!

**Comment by StrangerSon71** [comment]
Alright, hopefully a more convenient option becomes possible in the future, but at least it’s something!
